### ISSUE TITLE
Could u share PSGN baseline architectures

### ISSUE THREAD

**Issue by xiaomingjie** [val-iisc/densepcr#1]
HI @priyankamandikal 

According to ur paper, detailed network architectures for the baselines is provided in the supplementary. But I cant find where it is in WACV. As far as I know that origin PSGN only predicted 1,024 points while u made some changes to modify the number to 16,384. So could u share this version and tell where exactly the parameters are added?

Thank you

**Comment by priyankamandikal** [comment]
Hi, you can find the supplementary copy [here](https://priyankamandikal.github.io/downloads/wacv2019_DensePCR_suppl.pdf), which has architecture details for the baseline models and DensePCR.

**Comment by xiaomingjie** [comment]
solved. Thank u very much for ur lightning-speed reply.
